# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname First_Passage_Time
#' @export
fptpdf <- function(rt_r, parameter_r, is_positive_drift_r, verbose = FALSE) {
    .Call('_lbaModel_fptpdf', PACKAGE = 'lbaModel', rt_r, parameter_r, is_positive_drift_r, verbose)
}

#' @rdname First_Passage_Time
#' @export
fptcdf <- function(rt_r, parameter_r, is_positive_drift_r, verbose = FALSE) {
    .Call('_lbaModel_fptcdf', PACKAGE = 'lbaModel', rt_r, parameter_r, is_positive_drift_r, verbose)
}

#' @rdname First_Passage_Time
#' @export
n1PDF <- function(rt_r, parameter_r, is_positive_drift_r, verbose = FALSE) {
    .Call('_lbaModel_n1PDF', PACKAGE = 'lbaModel', rt_r, parameter_r, is_positive_drift_r, verbose)
}

#' @rdname lba_distributions
#' @export
dlba <- function(rt_r, parameter_r, is_positive_drift_r, debug = FALSE) {
    .Call('_lbaModel_dlba', PACKAGE = 'lbaModel', rt_r, parameter_r, is_positive_drift_r, debug)
}

#' @rdname lba_distributions
#' @export
plba <- function(rt_r, parameter_r, is_positive_drift_r, time_parameter_r, debug = FALSE) {
    .Call('_lbaModel_plba', PACKAGE = 'lbaModel', rt_r, parameter_r, is_positive_drift_r, time_parameter_r, debug)
}

#' @rdname rlba
#' @export
rlba_r <- function(parameter_r, is_positive_drift_r, time_parameter_r, n = 1L, use_inverse_method = FALSE, debug = FALSE) {
    .Call('_lbaModel_rlba_r', PACKAGE = 'lbaModel', parameter_r, is_positive_drift_r, time_parameter_r, n, use_inverse_method, debug)
}

#' @rdname lba_distributions
#' @export
theoretical_dlba <- function(parameter_r, is_positive_drift_r, time_parameter_r, debug = FALSE) {
    .Call('_lbaModel_theoretical_dlba', PACKAGE = 'lbaModel', parameter_r, is_positive_drift_r, time_parameter_r, debug)
}

#' @rdname lba_distributions
#' @export
theoretical_plba <- function(parameter_r, is_positive_drift_r, time_parameter_r, debug = FALSE) {
    .Call('_lbaModel_theoretical_plba', PACKAGE = 'lbaModel', parameter_r, is_positive_drift_r, time_parameter_r, debug)
}

#' @export
#' @rdname dlba_inverse_external
dlba_inverse_external <- function(rt_r, response_r, parameter_r, is_positive_drift_r, time_parameter_r) {
    .Call('_lbaModel_dlba_inverse_external', PACKAGE = 'lbaModel', rt_r, response_r, parameter_r, is_positive_drift_r, time_parameter_r)
}

#' @rdname lba_lowlevel
#' @export
validate_lba_parameters <- function(rt_model_r, parameters_r, debug = FALSE) {
    .Call('_lbaModel_validate_lba_parameters', PACKAGE = 'lbaModel', rt_model_r, parameters_r, debug)
}

#' @rdname lba_lowlevel
#' @export
simulate_lba_trials <- function(rt_model_r, parameters_r, n_trial = 1L, use_inverse_method = FALSE, debug = FALSE) {
    .Call('_lbaModel_simulate_lba_trials', PACKAGE = 'lbaModel', rt_model_r, parameters_r, n_trial, use_inverse_method, debug)
}

